"""Private Club initial reviewed schema
Revision ID: 0001_v8
"""
from alembic import op
import sqlalchemy as sa
revision="0001_v8";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("telegram_id",sa.Integer(),unique=True),sa.Column("telegram_username",sa.String(80)),sa.Column("role",sa.String(20),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("is_hidden",sa.Boolean(),nullable=False),sa.Column("contact_reveal",sa.Boolean(),nullable=False),sa.Column("risk_score",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("profiles",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),unique=True,nullable=False),sa.Column("alias",sa.String(80),nullable=False),sa.Column("age",sa.Integer(),nullable=False),sa.Column("city",sa.String(100),nullable=False),sa.Column("profile_type",sa.String(80),nullable=False),sa.Column("looking_for",sa.String(200),nullable=False),sa.Column("about",sa.Text(),nullable=False))
    op.create_table("profile_photos",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("telegram_file_id",sa.String(255),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.Column("approved",sa.Boolean(),nullable=False))
    op.create_table("consents",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("kind",sa.String(50),nullable=False),sa.Column("version",sa.String(20),nullable=False),sa.Column("accepted_at",sa.DateTime(),nullable=False))
    op.create_table("verifications",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("code",sa.String(12),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("media_file_id",sa.String(255)),sa.Column("media_type",sa.String(20)),sa.Column("note",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("reviewed_at",sa.DateTime()))
    op.create_table("likes",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("from_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("to_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("from_user_id","to_user_id"))
    op.create_table("matches",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user1_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("user2_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("user1_id","user2_id"))
    op.create_table("blocks",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("from_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("to_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("from_user_id","to_user_id"))
    op.create_table("complaints",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("from_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("to_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("audit_log",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("actor",sa.String(100),nullable=False),sa.Column("action",sa.String(80),nullable=False),sa.Column("target_user_id",sa.Integer()),sa.Column("detail",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("outbox",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("kind",sa.String(40),nullable=False),sa.Column("target_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("payload",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("attempts",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("sent_at",sa.DateTime()))
def downgrade():
    for t in ["outbox","audit_log","complaints","blocks","matches","likes","verifications","consents","profile_photos","profiles","users"]: op.drop_table(t)
